export const iconMap = {
  finances: 'mdi-cash-multiple',
  time: 'mdi-clock-outline',
  success: 'mdi-check-circle-outline',
  balance: 'mdi-scale-balance',
  categories: 'mdi-tag-multiple-outline',
  back: 'mdi-keyboard-return',
  history: 'mdi-history',
  next: 'mdi-arrow-right',
  energy: 'mdi-lightning-bolt-outline',
  currency: 'mdi-currency-brl',
  transfer: 'mdi-arrow-split-horizontal',
  identifier: 'mdi-identifier',
  calendar: 'mdi-calendar',
  company: 'mdi-domain',
  contactDetails: 'mdi-card-account-details',
  email: 'mdi-email',
  emailAlt: 'mdi-email-outline',
  document: 'mdi-clipboard-text-outline',
  edit: 'mdi-pencil',
  recordsList: 'mdi-clipboard-list-outline',
  userBadge: 'mdi-badge-account-outline',
  product: 'mdi-package-variant-outline',
  security: 'mdi-lock-outline',
  searchDocument: 'mdi-text-box-search-outline',
  userProfile: 'mdi-account-circle-outline',
  addUser: 'mdi-account-plus-outline',
  usersGroup: 'mdi-account-group-outline',
  disableUser: 'mdi-account-off-outline',
  inventory: 'mdi-package-variant-closed',
  notifications: 'mdi-bell-outline',
  databaseSearch: 'mdi-database-search-outline',
  home: 'mdi-home-outline',
  dashboard: 'mdi-view-dashboard-outline',
  packageSolid: 'mdi-package-variant',
  delivery: 'mdi-truck-delivery-outline',
  info: 'mdi-information-outline',
  circle: 'mdi-circle-outline',
  sun: 'mdi-weather-sunny',
  moon: 'mdi-weather-night',
} as const satisfies Record<string, string>

export type IconName = keyof typeof iconMap
